name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Dependencies
      run: |
        cd CWRU_RMP_REACT  # Navigate into the CWRU_RMP_REACT directory
        npm ci
    - name: Build the Project
      run: |
        cd CWRU_RMP_REACT  # Navigate into the CWRU_RMP_REACT directory
        npm run build --if-present
    - name: Run Tests
      run: |
        cd CWRU_RMP_REACT  # Navigate into the CWRU_RMP_REACT directory
        npm test
